export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDE_ALERT = 'HIDE_ALERT'
export const GET_REPOS = 'GET_REPOS'
export const GET_USER = 'GET_USER'
export const SET_LOADING = 'SET_LOADING'
export const REPO_LIST_EMPTY = 'REPO_LIST_EMPTY'
export const GET_USER_ERROR = 'GET_USER_ERROR'
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
export const SET_MEMO = 'SET_MEMO'

